---
  - hosts: all
    connection: local

    roles:
      - role: java
        java_version: '8.0.262+10'
      - role: stackdriver
        become: yes
        agent_type: monitoring
        package_state: present
        version: latest
      - role: stackdriver
        become: yes
        agent_type: logging
        package_state: present
        version: latest
      - role: actifio-agent
        become: yes
