---
  - hosts: all
    connection: local

    roles:
      - role: java
        java_version: '8.0.262+10'
      - role: stackdriver
        agent_type: monitoring
        package_state: present
        version: latest
        config_file_local: collectd.conf
        additional_config_dir: plugins/
